"""add_tournament_fields

Revision ID: 909f6c9d5461
Revises: a53d6a5eb83b
Create Date: 2025-06-28 14:27:20.821969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '909f6c9d5461'
down_revision: Union[str, None] = 'a53d6a5eb83b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('tournaments', sa.Column('location', sa.String(), nullable=False))
    op.add_column('tournaments', sa.Column('start_date', sa.Date(), nullable=False))
    op.add_column('tournaments', sa.Column('entry_fee', sa.Float(), nullable=False))
    op.add_column('tournaments', sa.Column('max_players', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'max_players')
    op.drop_column('tournaments', 'entry_fee')
    op.drop_column('tournaments', 'start_date')
    op.drop_column('tournaments', 'location')
    op.drop_column('tournaments', 'description')
    # ### end Alembic commands ###
