"""add average player rating to tournament

Revision ID: 72267b10abcf
Revises: 908cf7ecefe9
Create Date: 2025-09-28 11:03:05.774919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72267b10abcf'
down_revision: Union[str, None] = '908cf7ecefe9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('average_player_rating', sa.Float(), nullable=True))
    op.alter_column('tournaments', 'points_per_match',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tournaments', 'courts',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('tournaments', 'courts',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.alter_column('tournaments', 'points_per_match',
               existing_type=sa.INTEGER(),
               server_default=sa.text('32'),
               existing_nullable=False)
    op.drop_column('tournaments', 'average_player_rating')
    # ### end Alembic commands ###
