"""rename table

Revision ID: a53d6a5eb83b
Revises: edfa76be39f6
Create Date: 2025-06-28 14:09:55.851509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a53d6a5eb83b'
down_revision: Union[str, None] = 'edfa76be39f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournaments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('system', sa.Enum('AMERICANO', 'MEXICANO', name='tournamentsystem'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('current_round', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('tournament')
    op.drop_constraint('rounds_tournament_id_fkey', 'rounds', type_='foreignkey')
    op.create_foreign_key(None, 'rounds', 'tournaments', ['tournament_id'], ['id'])
    op.drop_constraint('tournament_player_tournament_id_fkey', 'tournament_player', type_='foreignkey')
    op.create_foreign_key(None, 'tournament_player', 'tournaments', ['tournament_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tournament_player', type_='foreignkey')
    op.create_foreign_key('tournament_player_tournament_id_fkey', 'tournament_player', 'tournament', ['tournament_id'], ['id'])
    op.drop_constraint(None, 'rounds', type_='foreignkey')
    op.create_foreign_key('rounds_tournament_id_fkey', 'rounds', 'tournament', ['tournament_id'], ['id'])
    op.create_table('tournament',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('system', postgresql.ENUM('AMERICANO', 'MEXICANO', name='tournamentsystem'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('current_round', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='tournament_created_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='tournament_pkey')
    )
    op.drop_table('tournaments')
    # ### end Alembic commands ###
