"""add_audit_log_table

Revision ID: e9d2657fba5a
Revises: a1b2c3d4e5f6
Create Date: 2025-10-02 12:56:37.767712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9d2657fba5a'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create ENUMs only if they don't exist (PostgreSQL-safe)
    connection = op.get_bind()

    # Check and create actiontype ENUM
    result = connection.execute(sa.text(
        "SELECT 1 FROM pg_type WHERE typname = 'actiontype'"
    )).fetchone()

    if not result:
        action_type_enum = sa.Enum(
            'USER_DELETE', 'USER_UPDATE', 'USER_STATUS_CHANGE',
            'TOURNAMENT_RESULT_EDIT', 'TOURNAMENT_SCORE_RECALC',
            'TOURNAMENT_STATUS_CHANGE', 'TOURNAMENT_DELETE',
            'SYSTEM_CONFIG_CHANGE',
            name='actiontype'
        )
        action_type_enum.create(connection, checkfirst=True)

    # Check and create targettype ENUM
    result = connection.execute(sa.text(
        "SELECT 1 FROM pg_type WHERE typname = 'targettype'"
    )).fetchone()

    if not result:
        target_type_enum = sa.Enum(
            'USER', 'TOURNAMENT', 'MATCH', 'ROUND', 'SYSTEM',
            name='targettype'
        )
        target_type_enum.create(connection, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('admin_id', sa.String(), nullable=True),
    sa.Column('action_type', sa.Enum('USER_DELETE', 'USER_UPDATE', 'USER_STATUS_CHANGE', 'TOURNAMENT_RESULT_EDIT', 'TOURNAMENT_SCORE_RECALC', 'TOURNAMENT_STATUS_CHANGE', 'TOURNAMENT_DELETE', 'SYSTEM_CONFIG_CHANGE', name='actiontype'), nullable=False),
    sa.Column('target_type', sa.Enum('USER', 'TOURNAMENT', 'MATCH', 'ROUND', 'SYSTEM', name='targettype'), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action_type'), 'audit_logs', ['action_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_target_id'), 'audit_logs', ['target_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_target_type'), 'audit_logs', ['target_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_target_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_target_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action_type'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
