"""Initial migration

Revision ID: edfa76be39f6
Revises: 
Create Date: 2025-06-22 10:40:46.327122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edfa76be39f6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('picture', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('tournament',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('system', sa.Enum('AMERICANO', 'MEXICANO', name='tournamentsystem', create_type=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('current_round', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rounds',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tournament_id', sa.String(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('team1_player1_id', sa.String(), nullable=False),
    sa.Column('team1_player2_id', sa.String(), nullable=False),
    sa.Column('team2_player1_id', sa.String(), nullable=False),
    sa.Column('team2_player2_id', sa.String(), nullable=False),
    sa.Column('team1_score', sa.Integer(), nullable=True),
    sa.Column('team2_score', sa.Integer(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['team1_player1_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['team1_player2_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['team2_player1_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['team2_player2_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tournament_player',
    sa.Column('tournament_id', sa.String(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], ),
    sa.PrimaryKeyConstraint('tournament_id', 'player_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tournament_player')
    op.drop_table('rounds')
    op.drop_table('tournament')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    
    # ### end Alembic commands ###
